default:
	#g++ helloworld.cpp;./a.out
	#g++ helloworldthread.cpp;./a.out
	#g++ callable.cpp ;./a.out
	#g++ listing_9.1.cpp --std=c++20;./a.out
	g++ listing_2.1t.cpp;./a.out
	g++ listing_2.1.cpp;./a.out

all1:
	g++ inheritancefromvector.cpp
	./a.out
