#!/usr/bin/python3
from github import Github
g=Github()
user=g.get_user("blueagle-so")
repos=user.get_repos()
non_forks = []
for repo in user.get_repos():
    if repo.fork is False:
        non_forks.append(repo.name)
print(non_forks)
